import type { Metadata } from 'next';
import { readFileSync } from 'fs';
import path from 'path';
import ReactMarkdown from 'react-markdown';
import RecordingEmbed from '@/components/fintechco/RecordingEmbed';
import OnboardingArtifact from './OnboardingArtifact';
import { HUB_CONFIG } from '@/lib/fintechco/config';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Day-Three Onboarding | FinTechCo Workspace',
  robots: { index: false, follow: false },
};

function getOnboardingData() {
  const base = path.join(process.cwd(), 'data/fintechco');
  const architecture = readFileSync(path.join(base, 'onboarding-architecture.md'), 'utf8');
  const doc = readFileSync(path.join(base, 'onboarding-doc.md'), 'utf8');
  const diff = readFileSync(path.join(base, 'onboarding-first-contribution.diff'), 'utf8');
  return { architecture, doc, diff };
}

export default function OnboardingAcceleratorPage() {
  const demo = HUB_CONFIG.demos.find((d) => d.key === 'onboarding')!;
  const { architecture, doc, diff } = getOnboardingData();

  return (
    <main className={styles.wrapper}>
      <a href="/fintechco" className={styles.backLink}>
        &larr; Back to workspace
      </a>

      <header className={styles.header}>
        <span className={styles.teamBadge}>Software Engineering</span>
        <h1 className={styles.title}>Day-Three Onboarding</h1>
        <p className={styles.framing}>
          What does a new engineer&apos;s third day look like when Claude Code is their guide?
          Starting from a cold clone of FinTechCo&apos;s multi-service payments codebase, Claude
          Code maps the architecture, identifies the right first contribution, ships a safe change
          with tests, and writes a handoff doc for the next engineer. Time-to-first-PR drops from
          days to hours.
        </p>
        <div className={styles.kpiRow}>
          <div className={styles.kpiCard}>
            <div className={styles.kpiValue}>Day 3</div>
            <div className={styles.kpiLabel}>First PR target</div>
          </div>
          <div className={styles.kpiCard}>
            <div className={styles.kpiValue}>14 / 14</div>
            <div className={styles.kpiLabel}>Tests passing</div>
          </div>
          <div className={styles.kpiCard}>
            <div className={styles.kpiValue}>&lt; 60s</div>
            <div className={styles.kpiLabel}>Onboarding run time</div>
          </div>
        </div>
      </header>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Demo Recording</h2>
        <RecordingEmbed recordingUrl={demo.recordingUrl} title="Onboarding accelerator demo" />
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Architecture Explainer</h2>
        <p className={styles.artifactNote}>
          Generated by Claude Code after reading the codebase cold. A 5-minute walk-through of
          service roles, data flow, and design decisions.
        </p>
        <div className={styles.markdownBlock}>
          <ReactMarkdown>{architecture}</ReactMarkdown>
        </div>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Onboarding Doc</h2>
        <p className={styles.artifactNote}>
          Supersedes the stale internal doc. Written for the next engineer joining the team.
        </p>
        <div className={styles.markdownBlock}>
          <ReactMarkdown>{doc}</ReactMarkdown>
        </div>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>First Contribution</h2>
        <p className={styles.artifactNote}>
          A contained, test-backed change identified and shipped during the onboarding session:
          currency validation added to the payments validator.
        </p>
        <OnboardingArtifact diff={diff} />
      </section>
    </main>
  );
}
