import type { Metadata } from 'next';
import { readFileSync } from 'fs';
import path from 'path';
import ReactMarkdown from 'react-markdown';
import RecordingEmbed from '@/components/fintechco/RecordingEmbed';
import FredKpiCards from '@/components/fintechco/FredKpiCards';
import { HUB_CONFIG } from '@/lib/fintechco/config';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Fed Policy to Portfolio Signal | FinTechCo Workspace',
  robots: { index: false, follow: false },
};

function getFredData() {
  const jsonPath = path.join(process.cwd(), 'data/fintechco/fred-summary.json');
  const memoPath = path.join(process.cwd(), 'data/fintechco/fred-executive-memo.md');
  const summary = JSON.parse(readFileSync(jsonPath, 'utf8'));
  const memo = readFileSync(memoPath, 'utf8');
  return { kpis: summary.kpis as FredKpis, memo };
}

export interface FredKpis {
  current_delinquency_rate: number;
  delinquency_trend: string;
  fedfunds_peak_lead_quarters: number;
  fedfunds_peak_correlation: number;
  unrate_peak_lead_quarters: number;
  model_r_squared: number;
}

export default function FredDashboardPage() {
  const demo = HUB_CONFIG.demos.find((d) => d.key === 'fred')!;
  const { kpis, memo } = getFredData();

  return (
    <main className={styles.wrapper}>
      <a href="/fintechco" className={styles.backLink}>
        &larr; Back to workspace
      </a>

      <header className={styles.header}>
        <span className={styles.teamBadge}>Data Science</span>
        <h1 className={styles.title}>Fed Policy to Portfolio Signal</h1>
        <p className={styles.framing}>
          Does the Federal Reserve&apos;s rate cycle predict consumer loan delinquency - and if so,
          how far in advance? Your data science team used Claude Code to pull FRED macro data,
          run a lagged regression, and ship an interactive dashboard in a single session. The
          result: an 8-quarter early-warning signal that gives credit risk teams a planning window
          before losses materialize.
        </p>
      </header>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Demo Recording</h2>
        <RecordingEmbed recordingUrl={demo.recordingUrl} title="FRED dashboard demo" />
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Key Findings</h2>
        <FredKpiCards kpis={kpis} />
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Interactive Dashboard</h2>
        <p className={styles.artifactNote}>
          The dashboard below was generated by Claude Code during the demo session. Explore the
          correlation heatmap and time-series overlay directly.
        </p>
        <div className={styles.dashboardFrame}>
          <iframe
            src={demo.artifactPath ?? '/presentations/fintechco/fred-dashboard.html'}
            title="FRED consumer delinquency dashboard"
            className={styles.dashboardIframe}
            sandbox="allow-scripts allow-same-origin"
          />
        </div>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Executive Memo</h2>
        <div className={styles.memo}>
          <ReactMarkdown>{memo}</ReactMarkdown>
        </div>
      </section>
    </main>
  );
}
