name: Generate Markdown from PDFs

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the workflow

jobs:
  Convert PDFs to Markdown and Generate Embeddings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Python script
        run: python scripts/convert_pdf_to_md.py  

      # If your script makes changes to files and you want to commit them:
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated changes by GitHub Actions" -a || echo "No changes to commit"
          git push

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # specify the Node.js version

      - name: Generate Embeddings
        run: node scripts/generate_embeddings.mjs